### ISSUE TITLE
如何实现真正的“自动”打卡

### ISSUE THREAD

**Issue by dundunnp** [hlsky1988/WeChatCheckingIn#1]
您好，我在实现一个健康打卡后，发现这完全不自动嘛:(，只是把打卡微信点击打卡的操作换成了打开hamibot的控制台点击运行脚本，这看起来这并没有更自动化，换汤不换药了。
**如何实现每天在某个时刻自动运行你的脚本（而不是自己手动点击）?**
_或许是我没仔细看完开发文档，求指教_

**Comment by hlskysong** [comment]
我的场景是丢一个手机在打卡地点远程触发，
你要是想要全程自动的话，hamibot控制台的定时任务可以看一下，
现在也提供API了，最好在自己服务器上做定时任务
