### ISSUE TITLE
咋用的？

### ISSUE THREAD

**Issue by wangweitung** [hlsky1988/WeChatCheckingIn#5]
咋用的？能否给个简明教程？

**Comment by hlskysong** [comment]
readme 有写，或者到 Hamibot 搜索相关的脚本看看，很久不用企业微信了，不能保证这个还能用

**Comment by wangweitung** [comment]
> readme 有写，或者到 Hamibot 搜索相关的脚本看看，很久不用企业微信了，不能保证这个还能用


谢谢，又了解了一个自动化工具【Hamibot】
